name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Simple Test
      run: |
        echo "Running Tests..."
        curl -s http://localhost:5000 || echo "Test simulated"  # Replace with real tests if needed

    - name: Build Docker Image
      run: docker build -t flask-cicd-app .

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: |
        docker tag flask-cicd-app pushpender123/flask-cicd-app:latest
        docker push pushpender123/flask-cicd-app:latest

    # --- NEW DEPLOYMENT STEP ---
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Kill any process using port 5000 
          sudo fuser -k 5000/tcp || true

          # Stop and remove any container using port 5000
          CONTAINER_ID=$(docker ps -q --filter "publish=5000")
          if [ -n "$CONTAINER_ID" ]; then
            docker stop $CONTAINER_ID || true
            docker rm $CONTAINER_ID || true
          fi

          docker pull pushpender123/flask-cicd-app:latest
          docker run -d -p 5000:5000 --name flask-cicd-app pushpender123/flask-cicd-app:latest
