name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Simple Test
      run: |
        echo "Running Tests..."
        curl -s http://localhost:5000 || echo "Test simulated"  # Replace with real tests if needed

    - name: Build Docker Image
      run: docker build -t flask-cicd-app .

    # Optional: Push to DockerHub
    # - name: Docker Login
    #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # - name: Push Docker Image
    #   run: docker tag flask-cicd-app yourdockerhub/flask-cicd-app && docker push yourdockerhub/flask-cicd-app

    # --- NEW DEPLOYMENT STEP ---
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd Flask-app
          git pull
          docker stop flask-cicd-app || true
          docker rm flask-cicd-app || true
          docker build -t flask-cicd-app .
          docker stop flask-cicd-app || true
          docker rm flask-cicd-app || true
          docker run -d -p 5000:5000 --name flask-cicd-app flask-cicd-app